### ISSUE TITLE
Find/Replace All takes ages

### ISSUE THREAD

**Issue by Sadi58** [KeithDHedger/KKEdit#1]
I think this happened in version 0.3.2:
When you perform Replace All in a large file, or rather for a large number of instances, the app window goes dark and (sometimes) it takes so long that you decide to quit.

**Comment by KeithDHedger** [comment]
Hi Sadi

Hadn't noticed this but I will check it out could you send me the file with the search terms you used, aslo are you using gtk2 or 3 version.
I have recently done a replace-all on all files on the kkedet source itself and didn't notice any problems, but these things do creep in.

Keith

Sent from Samsung tablet

-------- Original message --------

**Comment by Sadi58** [comment]
Hi Keith,
I use the new GTK3 version of KKEdit. I experience this issue for example when I try to replace all instances of 0.0.0.0 with 127.0.0.1 (or vice versa) in this file:
https://github.com/Sadi58/hostsblock/blob/master/indicator/hosts.txt

**Comment by KeithDHedger** [comment]
Until I can come up with a faster search/replace routine, try using a regex search with highlight  all turned off, after the first 'find' the replace is practically instant, but this is a big file>400k with ove 15000 replacements, it is going to be slow, but I will see what I can do in the next few days.
Made quick couple of change's to the repos helps a bit.

**Comment by KeithDHedger** [comment]
Fixed, much, MUCH faster, caseless replace is somewhat slower but can't be helped, with the search/replace that Sadi used for case sensitive time is approx 5 secs for caseless is about 30 secs,

**Comment by KeithDHedger** [comment]
As a P.S. unfortunately this loses any bookmarks on theat page I will look at this next.

**Comment by Sadi58** [comment]
Wov, this is really fast; thanks a lot!
I'll close this first issue here then :-)

**Comment by KeithDHedger** [comment]
As always Sadi you're welcome.
