### ISSUE TITLE
error: ‘gtk_source_completion_item_new’ was not declared

### ISSUE THREAD

**Issue by kuh3h3** [KeithDHedger/KKEdit#2]
tried to build git recent version on lubuntu 17.04 . but failed.
what is this error?

kuh3h3@reandro:~/KKEdit$ make
make  all-recursive
make[1]: 디렉터리 '/home/kuh3h3/KKEdit' 들어감
Making all in KKEdit/app
make[2]: 디렉터리 '/home/kuh3h3/KKEdit/KKEdit/app' 들어감
depbase=`echo ../src/completion.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I. -I../..  -I../.. -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2  -pthread -I/usr/include/libxml2 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/gtksourceview-2.0 -pthread -I/usr/include/webkitgtk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/webkitgtk-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DGTK_DISABLE_SINGLE_INCLUDES -DGDK_DISABLE_DEPRECATED -DGTK_DISABLE_DEPRECATED -DGSEAL_ENABLE -DPREFIX=\""/usr\"" -DLOCALEDIR=\""/usr/share/locale"\" -DDATADIR=\""/usr/share/KKEdit"\" -DSYSCONFDIR=\""/usr/etc/KKEdit"\" -DLIBDIR=\""/usr/lib/KKEdit"\" -DQT5DOCSDIR=\""/usr/share/doc/qt5"\" -DGTKSUPATH=\""gtksu -- "\" -D_DEBUGLEVEL_=0   -g -O2 -MT ../src/completion.o -MD -MP -MF $depbase.Tpo -c -o ../src/completion.o ../src/completion.cpp &&\
mv -f $depbase.Tpo $depbase.Po
../src/completion.cpp: In function ‘GList* addPropsFromWord(pageStruct*, char*, FunctionProvider*)’:
../src/completion.cpp:102:90: error: ‘gtk_source_completion_item_new’ was not declared in this scope
       newlist=g_list_append(newlist,gtk_source_completion_item_new(text,text,NULL,infostr));
                                                                                          ^
../src/completion.cpp: In function ‘void addProp(pageStruct*)’:
../src/completion.cpp:205:120: error: ‘gtk_source_completion_item_new’ was not declared in this scope
 =g_list_append(customProv->proposals,gtk_source_completion_item_new(buffer,buffer,NULL,NULL));
                                                                                            ^
../src/completion.cpp:221:134: error: ‘gtk_source_completion_item_new’ was not declared in this scope
 ncProv->proposals,gtk_source_completion_item_new(funcdata->name,funcdata->name,NULL,infostr));
                                                                                            ^
../src/completion.cpp:223:134: error: ‘gtk_source_completion_item_new’ was not declared in this scope
 rsProv->proposals,gtk_source_completion_item_new(funcdata->name,funcdata->name,NULL,infostr));
                                                                                            ^
Makefile:614: '../src/completion.o' 타겟에 대한 명령이 실패했습니다
make[2]: *** [../src/completion.o] 오류 1
make[2]: 디렉터리 '/home/kuh3h3/KKEdit/KKEdit/app' 나감
Makefile:397: 'all-recursive' 타겟에 대한 명령이 실패했습니다
make[1]: *** [all-recursive] 오류 1
make[1]: 디렉터리 '/home/kuh3h3/KKEdit' 나감
Makefile:338: 'all' 타겟에 대한 명령이 실패했습니다
make: *** [all] 오류 2

**Comment by kuh3h3** [comment]
Maybe your recent git made this error.
so i add this line to completion.cpp


#ifndef _USEGTK3_
#include <gtksourceview/gtksourcecompletionitem.h>
#endif

Now compile ok

**Comment by KeithDHedger** [comment]
Hi
Sorry you are having problems, I haven't come across this, I will check 
it out and get back to you ASAP

Keith

**Comment by KeithDHedger** [comment]
Hi
Yes you are correct, I was doing some code cleaning and got a bit 
carried away with removing redundant includes etc, fixed now so just do 
a git pull and it should fix your problem, sorry for the inconvenience, 
let me know if I can be of any more help.


Keith

**Comment by kuh3h3** [comment]
No, After make distclean, rebuild, but new error

../src/completion.cpp:23:2: error: ‘GObjectClass’ does not name a type
  GObjectClass   parent_class;
  ^~~~~~~~~~~~
../src/completion.cpp:27:24: error: expected constructor, destructor, or type conversion before ‘(’ token
 G_DEFINE_TYPE_WITH_CODE(FunctionProvider,function_provider,G_TYPE_OBJECT,G_IMPLEMENT_INTERFACE (GTK_TYPE_SOURCE_COMPLETION_PROVIDER,function_provider_iface_init))
                        ^
../src/completion.cpp:30:1: error: ‘FunctionProvider’ does not name a type
 FunctionProvider   *varsProv;
 ^~~~~~~~~~~~~~~~
../src/completion.cpp:31:1: error: ‘FunctionProvider’ does not name a type
 FunctionProvider   *customProv;
 ^~~~~~~~~~~~~~~~
../src/completion.cpp:34:1: error: ‘GtkSourceCompletionWords’ does not name a type
 GtkSourceCompletionWords *docWordsProv;
 ^~~~~~~~~~~~~~~~~~~~~~~~
../src/completion.cpp:36:1: error: ‘gchar’ does not name a type
 gchar *function_provider_get_name(GtkSourceCompletionProvider *provider)
 ^~~~~
../src/completion.cpp:41:1: error: ‘gint’ does not name a type
 gint function_provider_get_priority(GtkSourceCompletionProvider *provider)
 ^~~~
../src/completion.cpp:46:1: error: ‘gboolean’ does not name a type
 gboolean function_provider_match(GtkSourceCompletionProvider *provider,GtkSourceCompletionContext*context)
 ^~~~~~~~
../src/completion.cpp:51:24: error: ‘GtkTextIter’ was not declared in this scope
 char *get_word_at_iter(GtkTextIter *iter,GtkTextBuffer *buffer)
                        ^~~~~~~~~~~
../src/completion.cpp:51:37: error: ‘iter’ was not declared in this scope
 char *get_word_at_iter(GtkTextIter *iter,GtkTextBuffer *buffer)
                                     ^~~~
../src/completion.cpp:51:42: error: ‘GtkTextBuffer’ was not declared in this scope
 char *get_word_at_iter(GtkTextIter *iter,GtkTextBuffer *buffer)
                                          ^~~~~~~~~~~~~
../src/completion.cpp:51:57: error: ‘buffer’ was not declared in this scope
 char *get_word_at_iter(GtkTextIter *iter,GtkTextBuffer *buffer)
                                                         ^~~~~~
../src/completion.cpp:51:63: error: expression list treated as compound expression in initializer [-fpermissive]
 char *get_word_at_iter(GtkTextIter *iter,GtkTextBuffer *buffer)
                                                               ^
Makefile:614: '../src/completion.o' 타겟에 대한 명령이 실패했습니다
make[2]: *** [../src/completion.o] 오류 1
make[2]: 디렉터리 '/home/kuh3h3/KKEdit/KKEdit/app' 나감
Makefile:397: 'all-recursive' 타겟에 대한 명령이 실패했습니다
make[1]: *** [all-recursive] 오류 1
make[1]: 디렉터리 '/home/kuh3h3/KKEdit' 나감
Makefile:338: 'all' 타겟에 대한 명령이 실패했습니다
make: *** [all] 오류 2
kuh3h3@reandro:~/KKEdit$

**Comment by KeithDHedger** [comment]
Hi

I don't get that at this end so it may be a problem with one of the libs 
used bu *buntu, they are always hacking the gtk libs to keep there awful 
desktops working, but that's a rant for another time :)

Can you send me the configure command you used, I dont have a copy of 
lubuntu so I will download a iso and run up a virtual machine and see if 
I can sort this out.

In the mean time you can try grabbing a fresh repo via git clone, 
sometimes this helps, at least I have found it helps with apps like 
ffmpeg, anyway give it a try.

Thanks

Keith

**Comment by kuh3h3** [comment]
thanks, your fix is ok. now no problems
any special option not used

./configure --prefix=/usr

**Comment by KeithDHedger** [comment]
Hi
Glad it's sorted, let me know if I can be of any further help.

Have fun!

Keith
